[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
spin = "0.9.8"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"
lto = true